# Dependabot configuration for automatic dependency updates
version: 2
updates:
  # Enable version updates for Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    assignees:
      - "CaroVisentin"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "09:00"
    commit-message:
      prefix: "ci"
    labels:
      - "github-actions"
      - "automated"