name: Android CI
run-name: ${{ github.actor }} building MathRacer! 🚀

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  JAVA_VERSION: '17'  # Required by Android Gradle Plugin

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: temurin
        cache: gradle
        
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
      
    - name: Build project
      run: ./gradlew assembleDebug --stacktrace
      
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest --stacktrace
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-artifacts
        path: |
          app/build/outputs/apk/
          app/build/reports/
        retention-days: 30