name: Android Lint 🧹
run-name: ${{ github.actor }} scanning code quality! 🛡️

on:
  pull_request:
    branches: [main, dev]
    paths:
      - .github/workflows/android-lint.yml
      - 'app/src/**'
      - gradle/**
      - '**.gradle'
      - '**.gradle.kts'
      - gradle.properties
      - gradlew*

jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
          
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      - name: Run Android Lint
        run: ./gradlew lintDebug --stacktrace
        
      - name: Upload lint reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          path: |
            app/build/reports/lint-results-*.html
            app/build/reports/lint-results-*.xml
          retention-days: 30