name: Test Coverage ✅
run-name: ${{ github.actor }} ensuring code quality with tests! 🧪

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test-coverage:
    permissions: write-all
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
          
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest
        
      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Test Results
          path: '**/TEST-*.xml'
          reporter: java-junit
          fail-on-error: true
          
      - name: Add test results to PR
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            **/test-results/**/*.xml
          comment_mode: create new
          check_name: "Unit Test Results"